
package es.udc.ws.app.client.service.soap.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OfferProviderService", targetNamespace = "http://soap.ws.app.udc.es/", wsdlLocation = "file:/home/tk/Desktop/software/ws-app/ws-app-service/target/generated-sources/wsdl/OfferProviderService.wsdl")
public class OfferProviderService
    extends Service
{

    private final static URL OFFERPROVIDERSERVICE_WSDL_LOCATION;
    private final static WebServiceException OFFERPROVIDERSERVICE_EXCEPTION;
    private final static QName OFFERPROVIDERSERVICE_QNAME = new QName("http://soap.ws.app.udc.es/", "OfferProviderService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/tk/Desktop/software/ws-app/ws-app-service/target/generated-sources/wsdl/OfferProviderService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        OFFERPROVIDERSERVICE_WSDL_LOCATION = url;
        OFFERPROVIDERSERVICE_EXCEPTION = e;
    }

    public OfferProviderService() {
        super(__getWsdlLocation(), OFFERPROVIDERSERVICE_QNAME);
    }

    public OfferProviderService(WebServiceFeature... features) {
        super(__getWsdlLocation(), OFFERPROVIDERSERVICE_QNAME, features);
    }

    public OfferProviderService(URL wsdlLocation) {
        super(wsdlLocation, OFFERPROVIDERSERVICE_QNAME);
    }

    public OfferProviderService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, OFFERPROVIDERSERVICE_QNAME, features);
    }

    public OfferProviderService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OfferProviderService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OfferProvider
     */
    @WebEndpoint(name = "OfferProviderPort")
    public OfferProvider getOfferProviderPort() {
        return super.getPort(new QName("http://soap.ws.app.udc.es/", "OfferProviderPort"), OfferProvider.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OfferProvider
     */
    @WebEndpoint(name = "OfferProviderPort")
    public OfferProvider getOfferProviderPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.ws.app.udc.es/", "OfferProviderPort"), OfferProvider.class, features);
    }

    private static URL __getWsdlLocation() {
        if (OFFERPROVIDERSERVICE_EXCEPTION!= null) {
            throw OFFERPROVIDERSERVICE_EXCEPTION;
        }
        return OFFERPROVIDERSERVICE_WSDL_LOCATION;
    }

}
