
package es.udc.ws.app.client.service.soap.wsdl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "SoapReservationTimeExpiredException", targetNamespace = "http://soap.ws.app.udc.es/")
public class SoapReservationTimeExpiredException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private SoapReservationTimeExpiredExceptionInfo faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public SoapReservationTimeExpiredException(String message, SoapReservationTimeExpiredExceptionInfo faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public SoapReservationTimeExpiredException(String message, SoapReservationTimeExpiredExceptionInfo faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: es.udc.ws.app.client.service.soap.wsdl.SoapReservationTimeExpiredExceptionInfo
     */
    public SoapReservationTimeExpiredExceptionInfo getFaultInfo() {
        return faultInfo;
    }

}
