#! /bin/sh

### BEGIN INIT INFO
# Provides: mysqld 
# Required-Start:
# Required-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: My python server
# Description: My script is cool
### END INIT INFO

. /lib/lsb/init-functions
NAME=mysqld
DAEMON=/opt/mysql/bin/mysqld
PIDFILE=/home/bougar/software/.MySQLData/mysqld.pid
SQLADMIN=/opt/mysql/bin/mysqladmin


test -x $DAEMON || exit 5
case $1 in
start)
	if [ -e $PIDFILE ];
	then
		status_of_proc -p $PIDFILE $DAEMON "$NAME" && status="0" || status="$?"
		if  [ "$status" = "0" ];
		then
			exit
		fi
	fi
	#Some logging
	log_success_msg "Starting the process" "$NAME"
	#Start the daemon
	if start-stop-daemon --start --quiet --oknodo -b --pidfile $PIDFILE --exec "$DAEMON" --name $NAME -- --defaults-file=/opt/mysql/my.cnf;
	then
		if [ -e $PIDFILE ]
		then
			read pid < "$PIDFILE"
			if  ! ps "${pid:-}" >/dev/null 2>&1 ; 
			then
				log_failure_msg "Could not start the proccess"
				/bin/rm -rf $PIDFILE
				log_end_msg 1
				exit 1
			fi
		fi
		log_end_msg 0	
	else
		log_end_msg 1
	fi
;;
stop)
	if [ -e $PIDFILE ];
	then
		status_of_proc -p $PIDFILE $DAEMON "$NAME" && status="0" || status="$?"
		if [ "$status" = "0" ];
		then
			$SQLADMIN  --defaults-file=/opt/mysql/my.cnf -u root shutdown	
			log_success_msg "The proccess has been stoped"
			/bin/rm -rf $PIDFILE
		fi
	else
		log_failure_msg "Not pidfile found"
	fi
;;
restart)
	$0 stop && sleep 2 && $0 start
;;
status)
	status_of_proc -p $PIDFILE $DAEMON "$NAME process" && status="0" || status="$?"
;;
reload)
	log_daemon_msg "Not implemented yet"
;;
*)
	echo "Usage: $0 {start|stop|restart|reload|status}"
	exit 2
;;
esac
